server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import:
      - optional:config/env.yml
  datasource:
    url: "${app.datasource.mariadb.url}"
    username: "${app.datasource.mariadb.username}"
    password: "${app.datasource.mariadb.password}"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.type.descriptor.sql: trace